---
- hosts: all
  become: true

  tasks:
    - name: create user
      ansible.builtin.user:
        name: test-user
        password: "{{ 'test_password' | ansible.builtin.password_hash('sha512') }}"
        uid: 1050
        shell: /usr/bin/bash
