---
- hosts: linux_all
  become: true

  tasks:
    - name: create user
      ansible.builtin.user:
        name: sample-user
        password: "{{ 'sample_password' | ansible.builtin.password_hash('sha512') }}"
        uid: 1050
        shell: /usr/bin/bash
